### ISSUE TITLE
gLabels File Chooser not working with the portals

### ISSUE THREAD

**Issue by etrigan63** [flathub/org.gnome.glabels-3#1]
The current flatpak will not allow me to save files and can only see parts of the file system. I had to issue `flatpak override --user --filesystem=home org.gnome.glabels-3` to allow it to write to my home folder.

**Comment by nedrichards** [comment]
Right, that's very much an issue to file with the upstream project https://github.com/jimevins/glabels asking them to use https://developer.gnome.org/gtk3/stable/gtk3-GtkFileChooserNative.html

**Comment by nedrichards** [comment]
Apologies, I may have been hasty in my response. Will spend a little longer debugging as that doesn't look right.

**Comment by nedrichards** [comment]
So yeah, it'd be great if upstream used filechoosernative, but until then I'll add the home permission. Thanks for reporting.

**Comment by nedrichards** [comment]
Should be fixed by https://github.com/flathub/org.gnome.glabels-3/commit/57b4ccaa1c9c168f101deabdd5f035975f34a35b
